import { useState, useEffect } from "react";
import "./App.css";

// Import Components
import HistoryView from "./components/HistoryView";
import StepDecision from "./components/StepDecision";
import StepOptions from "./components/StepOptions";
import StepCriteria from "./components/StepCriteria";
import StepScoring from "./components/StepScoring";
import StepResults from "./components/StepResults";

function App() {
	const [step, setStep] = useState(1);
	const [title, setTitle] = useState("");
	const [category, setCategory] = useState("");
	const [options, setOptions] = useState(["", ""]);
	const [criteria, setCriteria] = useState([
		{ name: "", weight: 3 },
		{ name: "", weight: 3 },
	]);
	const [scores, setScores] = useState({});
	const [results, setResults] = useState(null);
	const [loading, setLoading] = useState(false);
	const [history, setHistory] = useState([]);
	const [viewingHistory, setViewingHistory] = useState(false);

	// Load history on mount
	useEffect(() => {
		const saved = localStorage.getItem("dcs_history");
		if (saved) {
			try {
				setHistory(JSON.parse(saved));
			} catch (e) {
				console.error("Failed to parse history", e);
			}
		}
	}, []);

	// Save to history
	const saveToHistory = (decisionResult) => {
		const newEntry = {
			id: Date.now(),
			date: new Date().toLocaleString(),
			title: title || "Untitled Decision",
			category: category || "General",
			...decisionResult,
		};
		const updatedHistory = [newEntry, ...history];
		setHistory(updatedHistory);
		localStorage.setItem("dcs_history", JSON.stringify(updatedHistory));
	};

	// Download Decision as Text
	const downloadDecision = (decision) => {
		const fileName = `${decision.title.replace(/\s+/g, "_")}_Report.txt`;
		let content = `DECISION REPORT: ${decision.title}\n`;
		content += `Date: ${decision.date || new Date().toLocaleString()}\n`;
		content += `Category: ${decision.category}\n`;
		content += `------------------------------------------\n\n`;
		content += `WINNER: ${decision.winner}\n`;
		content += `Insight: ${decision.insight}\n\n`;
		content += `RANKINGS:\n`;

		Object.entries(decision.ranked_results).forEach(([opt, data], i) => {
			content += `${i + 1}. ${opt} (Score: ${data.final.toFixed(2)}/10)\n`;
			data.breakdown.forEach((b) => {
				content += `   - ${b.criterion}: Score ${b.score}, Weight ${b.weight} (Total: ${b.weighted_score})\n`;
			});
			content += `\n`;
		});

		content += `------------------------------------------\n`;
		content += `Generated by Decision Companion System`;

		const element = document.createElement("a");
		const file = new Blob([content], { type: "text/plain" });
		element.href = URL.createObjectURL(file);
		element.download = fileName;
		document.body.appendChild(element);
		element.click();
		document.body.removeChild(element);
	};

	// Handlers for Options
	const handleOptionChange = (index, value) => {
		const newOptions = [...options];
		newOptions[index] = value;
		setOptions(newOptions);
	};
	const addOption = () => setOptions([...options, ""]);
	const removeOption = (index) =>
		setOptions(options.filter((_, i) => i !== index));

	// Handlers for Criteria
	const handleCriterionChange = (index, field, value) => {
		const newCriteria = [...criteria];
		newCriteria[index][field] = value;
		setCriteria(newCriteria);
	};
	const addCriterion = () =>
		setCriteria([...criteria, { name: "", weight: 3 }]);
	const removeCriterion = (index) =>
		setCriteria(criteria.filter((_, i) => i !== index));

	// Handlers for Scores
	const handleScoreChange = (option, criterionName, value) => {
		setScores((prev) => ({
			...prev,
			[option]: {
				...(prev[option] || {}),
				[criterionName]: parseInt(value, 10) || 0,
			},
		}));
	};

	// Submission
	const evaluateDecision = async () => {
		setLoading(true);
		try {
			const validOptions = options.filter((o) => o.trim() !== "");
			const validCriteria = criteria.filter((c) => c.name.trim() !== "");

			const response = await fetch("/api/evaluate", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					options: validOptions,
					criteria: validCriteria,
					scores: scores,
				}),
			});

			const data = await response.json();
			setResults(data);
			saveToHistory(data);
			setStep(5);
		} catch (error) {
			console.error("Error evaluating decision:", error);
			alert("Failed to evaluate decision. Check console for details.");
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className="container">
			<header className="header">
				<h1>🧭 Decision Companion</h1>
				<p>Weighted decisions. Clearer choices.</p>
				<button
					className="history-toggle"
					onClick={() => setViewingHistory(!viewingHistory)}
				>
					{viewingHistory ? "Back to App" : "📜 History"}
				</button>
			</header>

			<main className="card">
				{viewingHistory ? (
					<HistoryView
						history={history}
						setTitle={setTitle}
						setCategory={setCategory}
						setResults={setResults}
						setViewingHistory={setViewingHistory}
						setStep={setStep}
						downloadDecision={downloadDecision}
					/>
				) : (
					<>
						{step === 1 && (
							<StepDecision
								title={title}
								setTitle={setTitle}
								category={category}
								setCategory={setCategory}
								setStep={setStep}
							/>
						)}

						{step === 2 && (
							<StepOptions
								options={options}
								handleOptionChange={handleOptionChange}
								addOption={addOption}
								removeOption={removeOption}
								setStep={setStep}
							/>
						)}

						{step === 3 && (
							<StepCriteria
								criteria={criteria}
								handleCriterionChange={handleCriterionChange}
								addCriterion={addCriterion}
								removeCriterion={removeCriterion}
								setStep={setStep}
							/>
						)}

						{step === 4 && (
							<StepScoring
								options={options}
								criteria={criteria}
								scores={scores}
								handleScoreChange={handleScoreChange}
								evaluateDecision={evaluateDecision}
								loading={loading}
								setStep={setStep}
							/>
						)}

						{step === 5 && results && (
							<StepResults
								title={title}
								category={category}
								results={results}
								downloadDecision={downloadDecision}
								setStep={setStep}
								setResults={setResults}
								setTitle={setTitle}
								setCategory={setCategory}
							/>
						)}
					</>
				)}
			</main>
		</div>
	);
}

export default App;
